query records(
  $id: ID
  $relation_tables: [String]!
  $name: String
  $page: Int = 1
  $r_id: String
  $l_id: String
  $not_l_id: [String!]
  $limit: Int!
  $include_related: Boolean = false
  $accepted: Boolean
  $approved: Boolean
){
  records(
    per_page: $limit
    page: $page
    filter: {
      id: { value: $id }
      table: { value: "modules/community/relationship" }
      properties: [
        { name: "name" starts_with: $name }
        { name: "r_id" value: $r_id }
        { name: "l_id" value: $l_id, not_value_in: $not_l_id }
        { name: "l_accepted_at" exists: $accepted }
        { name: "r_accepted_at" exists: $approved }
      ]
    }
  ){
    total_entries
    total_pages
    has_previous_page
    has_next_page
    results {
      id
      type: table
      created_at
      created_by_id: property(name: "created_by_id")
      name: property(name: "name")
      r_id: property(name: "r_id")
      l_id: property(name: "l_id")
      r_accepted_at: property(name: "r_accepted_at")
      l_accepted_at: property(name: "l_accepted_at")

      l: related_record(foreign_property: "id" join_on_property: "l_id" table: $relation_tables) @include(if: $include_related) {
        ...record
      }
      r: related_record(foreign_property: "id" join_on_property: "r_id" table: $relation_tables) @include(if: $include_related) {
        ...record
      }
    }
  }
}

fragment record on Record {
  id
  type: table
  user_id: property(name: "user_id")
  uuid: property(name: "uuid")
  name: property(name: "name")
  first_name: property(name: "first_name")
  last_name: property(name: "last_name")
  slug: property(name: "slug")
  post_count: property_int(name: "post_count")
  status: property(name: "status")
  follower_count: property_int(name: "follower_count")
  uuid: property(name: "uuid")
  properties

  avatar: related_record(table: "modules/community/photo", join_on_property: "uuid", foreign_property: "object_uuid", filter: { properties: { name: "photo_type", value: "avatar"}}) {
    photo_width: property_int(name: "photo_width")
    photo_height: property_int(name: "photo_height")
    photo: property_upload(name: "photo") {
      url
      versions
    }
  }
}

