query search(
  $id: ID
  $limit: Int = 20
  $page: Int = 1
  $sort: RecordsSortInput = { created_at: { order: DESC } }
  $name: String
  $keyword: String
  $not_name: String
  $not_ids: [ID!]
  $owner_id: String
  $relation_name: String
  $with_owner: Boolean = false
  $profile_table: [String]!
  $relationships: Boolean = false
  $status: [String!] = ["published"]
  $from: String
) {
  events: records(
    per_page: $limit
    page: $page
    filter: {
      id: { value: $id, not_value_in: $not_ids }
      table: { value: "modules/community/event" }
      properties: [
        { name: "status", value_in: $status }
        { name: "name", value: $name }
        { name: "name", not_value: $not_name }
        { name: "start_date", range: { gte: $from }}
      ]
      or: [
        { properties:  { name: "name", contains: $keyword } }
        { properties: { name: "short_description", contains: $keyword } }
        { properties: { name: " description", contains: $keyword } }
      ]
      related_records: {
        join: { join_on_property: "id", foreign_property: "r_id" }
        filter: {
          table: { value: "modules/community/relationship" }
          properties: [
            { name: "l_id", value: $owner_id }
            { name: "name", value: $relation_name }
          ]
        }
      }
    }
    sort: [$sort]
  ) {
    total_entries
    total_pages
    has_previous_page
    has_next_page
    results {
      ...event
    }
  }
}

fragment event on Record {
  id
  created_at
  type: table

  event_uuid: property(name: "event_uuid")
  uuid: property(name: "uuid")
  name: property(name: "name")
  short_description: property(name: "short_description")
  description: property(name: "description")
  start_date: property(name: "start_date")
  end_date: property(name: "end_date")
  link: property(name: "link")
  venue: property(name: "venue")
  commentable: property_boolean(name: "commentable")
  status: property(name: "status")
  c__going: property_int(name: "c__going")
  c__maybe: property_int(name: "c__maybe")
  c__not_going: property_int(name: "c__not_going")

  photo: related_record(table: "modules/community/photo", join_on_property: "uuid", foreign_property: "object_uuid") {
    id
    photo_width: property_int(name: "photo_width")
    photo_height: property_int(name: "photo_height")
    photo: property_upload(name: "photo") {
      url
      versions
    }
  }
  owner: related_record(
    table: "modules/community/relationship"
    join_on_property: "id"
    foreign_property: "r_id"
    filter: { properties: { value: "owner", name: "name" } }
  ) @include(if: $with_owner) {
    id
    properties
    profile: related_record(table: $profile_table, join_on_property: "l_id") {
      id
      type: table
      properties
      name: property(name: "name")
      first_name: property(name: "first_name")
      last_name: property(name: "last_name")
      slug: property(name: "slug")
      avatar: related_record(
        table: "modules/community/photo"
        join_on_property: "uuid"
        foreign_property: "object_uuid"
        filter: { properties: { name: "photo_type", value: "avatar" } }
      ) {
        photo_width: property_int(name: "photo_width")
        photo_height: property_int(name: "photo_height")
        photo: property_upload(name: "photo") {
          url
          versions
        }
      }
    }
  }

  relationships: related_records(table: "modules/community/relationship" join_on_property: "id" foreign_property: "r_id") @include(if: $relationships) {
    id
    name: property(name: "name")
    r_id: property(name: "r_id")
    l_id: property(name: "l_id")
  }
}

