query profiles_search(
  $page: Int = 1
  $limit: Int = 20
  $first_name: String
  $last_name: String
  $email: String
  $emails: [String!]
  $id: ID
  $ids: [ID!]
  $not_ids: [ID!]
  $uuid: String
  $user_id: String
  $sort: RecordsSortInput = { created_at: { order: DESC } }
  $roles: [String!]
  $query: String
  $with_avatar: Boolean = true
  $with_profile_cover: Boolean = false
  $with_user: Boolean = false
) {
  records(
    page: $page
    per_page: $limit
    filter: {
      id: { value: $id, value_in: $ids, not_value_in: $not_ids }
      table: { value: "modules/user/profile" }
      properties: [
        { name: "uuid", value: $uuid }
        { name: "first_name", value: $first_name }
        { name: "last_name", value: $last_name }
        { name: "user_id", value: $user_id }
        { name: "email", value: $email, value_in: $emails }
        { name: "c__names", contains: $query }
      ]
      related_users: {
        join: { join_on_property: "user_id", foreign_property: "id" }
        filter: { properties: [
          { name: "roles", array_overlaps: $roles }
        ]}
      }
    }
    sort: [$sort]
  ) {
    total_entries
    total_pages
    has_previous_page
    has_next_page
    results {
      id
      created_at
      updated_at
      type: table
      properties
      email: property(name: "email")
      first_name: property(name: "first_name")
      last_name: property(name: "last_name")
      name: property(name: "name")
      user_id: property(name: "user_id")
      uuid: property(name: "uuid")
      roles: property_array(name: "roles")
      post_count: property(name: "post_count")
      avatar: related_record(
        table: "modules/community/photo"
        join_on_property: "uuid"
        foreign_property: "object_uuid"
        filter: { properties: { name: "photo_type", value: "avatar" } }
      ) @include(if: $with_avatar) {
        photo_width: property_int(name: "photo_width")
        photo_height: property_int(name: "photo_height")
        photo: property_upload(name: "photo") {
          url
          versions
        }
      }
      profile_cover: related_record(
        table: "modules/community/photo"
        join_on_property: "uuid"
        foreign_property: "object_uuid"
        filter: { properties: { name: "photo_type", value: "profile_cover" } }
      ) @include(if: $with_profile_cover) {
        photo_width: property_int(name: "photo_width")
        photo_height: property_int(name: "photo_height")
        photo: property_upload(name: "photo") {
          url
          versions
        }
      }
      user: related_user(
        join_on_property: "user_id"
        foreign_property: "id"
      ) @include(if: $with_user) {
        id
        email
        roles: property_array(name: "roles")
      }
    }
  }
}
