mutation profiles_update(
  $id: ID!
  $name: String
  $first_name: String
  $last_name: String
  $email: String
  $c__names: String
  $timezone: String
) {
  record: record_update(
    id: $id
    record: {
      table: "modules/user/profile"
      properties: [
        { name: "name", value: $name }
        { name: "first_name", value: $first_name }
        { name: "last_name", value: $last_name }
        { name: "email", value: $email }
        { name: "c__names", value: $c__names }
        { name: "timezone", value: $timezone }
      ]
    }
  ) {
    id
    created_at
    type: table

    email: property(name: "email")
    first_name: property(name: "first_name")
    last_name: property(name: "last_name")
    name: property(name: "name")
    user_id: property(name: "user_id")
    uuid: property(name: "uuid")
    roles: property_array(name: "roles")
    timezone: property(name: "timezone")
    post_count: property(name: "post_count")
  }
}
