query (
  $id: ID
  $limit: Int = 20
  $page: Int = 1
  $name: String
  $slug: String
  $status: String
) {
  static_pages: records(
    per_page: $limit
    page: $page
    filter: {
      id: { value: $id }
      table: { value: "static_page" }
      properties: [
        { name: "name", value: $name }
        { name: "slug", value: $slug }
        { name: "status", value: $status }
      ]
    }
    sort: [{ created_at: { order: DESC } }]
  ) {
    total_entries
    has_next_page

    results {
      id
      created_at
      updated_at
      type: table

      name: property(name: "name")
      slug: property(name: "slug")
      status: property(name: "status")
    }
  }
}
