mutation create_tag(
  $name: String!
  $post_count: Int = 0
  $status: String = "published"
  $follower_count: Int = 0
  $disabled_at: String
  $creator_id: String
) {
  record: record_create(
    record: {
      table: "modules/community/tag"
      properties: [
        { name: "name" value: $name }
        { name: "post_count" value_int: $post_count }
        { name: "follower_count" value_int: $follower_count }
        { name: "status" value: $status }
        { name: "disabled_at" value: $disabled_at }
        { name: "creator_id" value: $creator_id }
      ]
    }
  ){
    id
    created_at
    deleted_at

    name: property(name: "name")
    post_count: property_int(name: "post_count")
    follower_count: property_int(name: "follower_count")
    status: property(name: "status")
    disabled_at: property(name: "disabled_at")
    creator_id: property(name: "creator_id")
  }
}
